{
 "title": "algotrading",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory usage (byte)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orderbook avg latency (sec.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "orderbook_avg_processing_latency_seconds{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Single orderbook latency (sec.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "orderbook_single_processing_latency_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trade signal latency (sec.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "trade_signal_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Trade order latency (sec.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "order_execution_latency_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataloss count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "dataloss_error_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "error_count", "legendFormat": "__auto" }
   ]
  }
 ]
}